[#g2,reftext=G.2]
=== (G.2) Current situation

ifdef::env-draft[]
TIP: _Current state of processes to be addressed by the project and the resulting system. It describes the current situation, upon which the system is expected to improve_  <<BM22>>
endif::[]

The McMaster Engineering Society (MES) organizes many large student events on the McMaster University campus intended to attract hundreds of attendees. The current state of processes involved in running these events, from registration and ticketing to event updates are oftentimes scattered across multiple third-party platforms and tools such as Discord servers, Instagram stories and Google Forms. Due to this scattered approach, several barriers and inefficiencies are created for both students intending to participate in events organized by the MES and organizers dedicating their time to event logistics. From the perspective of attendees, there is frustration and a struggle to stay up to date and access clear information regarding event logistics. The scattered nature of information sources results in confusion, as attendees are forced to navigate multiple social media platforms or forms to stay up to date on events and complete a single registration. The result can be missed deadlines or uncertainty around event arrangements from seating to transportation arrangements. Additionally, the absence of centralized notifications further diminishes the experience, as the possibility of missing critical updates or reminders increases which can impact the event attendance of users. From the organizers perspective, there is a significant load in administrative work. Managing ticketing and signups across multiple platforms is time-consuming and with the added work of tracking accessibility requests and waivers can further increase the likelihood of omissions or errors in tracking. Overall, the current uncentralized process increases administrative overhead work for organizers reducing their efficiency and reduces the quality of experience for attendees, negatively impacting their experiences.
