[#p1,reftext=P.1]
=== (P.1) Roles and personnel

ifdef::env-draft[]
TIP: _Main responsibilities in the project; required project staff and their needed qualifications. It defines the roles (as a human responsibility) involved in the project._  <<BM22>>
endif::[]

* *Security Expert*: The responsibility of the security expert entails working to define security requirements and policies that hinge on the CIA triad (Confidentiality, Integrity, Availability) as well as immobilization of threats when they arise which would require them to have prior experience in dealing with the four main types of threats: disclosure, deception, disruption and usurpation. The qualifications of the security expert will typically include a bachelor's degree in a field such as Computer Science, Information Security or Cybersecurity as well as relevant personal or work experience in a relevant field in security.

* *Product Owner*: The product owner is responsible for representing the interest of the customer and market which entails responsibility for the overall product. The encompassing responsibilities range from organization of product backlog of features, ensuring alignment with company goals and vision to understanding stakeholder needs and requirements. The qualifications of the product owner will typically involve a Bachelor's degree in either a technical field related to Engineering, Computer Science or a business field such as Management or Business Administration as well as strong understanding of meeting client and stakeholder needs.

* *Developers*: The responsibility of developers revolves around the development of various technical components and core functionalities of the project on the front end and backend. The qualifications of developers typically will include a Bachelor’s degree in Computer Science, Engineering, or equivalent fields. It will also generally require experience in application development, payment integration as well as modern frameworks for both mobile and web application development.

* *Quality Testers (Quality Engineers/Quality Assurance)*: The quality testers are responsible for ensuring system reliability of the product through testing and validation. Their focus is on technical aspects of the project to ensure alignment with defined quality standards, requirements and specifications. The qualifications of quality testers typically includes a Bachelor’s degree in Computer Science, Engineering, or equivalent fields and generally requires experience with modern testing frameworks and tools. Specifically, having an understanding of defining, designing and implementing test cases and test plans based on requirements.
