[#p6,reftext=P.6]
=== (P.6) Risk and mitigation analysis

ifdef::env-draft[]
TIP: _Potential obstacles to meeting the schedule of <<p4>>, and measures for adapting the plan if they do arise. It is essential to be on the lookout for events that could derail the project, and devise mitigation strategies. It can include a SWOT analysis (Strengths, Weaknesses, Opportunities, Threats) for the project._  <<BM22>>
endif::[]


==== Risk Analysis

* *Difficulty in integrating payment gateways:* An important part of the system is being able to integrate payment gateways for safe and secure purchasing of event tickets for users. However, there are multiple risks that can arise such as transaction delays or API changes that could disrupt the payment processes. The result of these issues can be failed or duplicate transactions which can frustrate users as well as payments not being processed in time resulting in difficulties for organizers planning paid events. A couple of mitigation strategies for this risk can be incorporating an option for multiple different payment gateways for multiple different providers in case one fails and scheduling regular maintenance or updates to verify API compatibility. Additionally, integrating transaction logs with fail-safe mechanisms for retrying on failures and emailing confirmation receipts can help prevent loss of payment and improve reliability which can prevent any frustration or unease for users while at the same time keeping a dependable trace of data for organizers.

* *Possible security and privacy vulnerabilities related to role based accesses:* With the role based and feature based access control the application provides, it also introduces potential security and privacy vulnerabilities. For instance, incorrectly configured access validation could expose sensitive data such as user payment information or admin dashboard details to unauthorized users, which could violate university policies on data handling. There can also be a risk of violating privacy laws if the data is not handled properly which can result in lawsuits, fines and damage to reputation. Additionally, if the perceived notion from users is that their data is not being handled properly, it could lead to distrust and a loss in user retention and user growth. Mitigation strategies for this risk on the user side would include implementing end-to-end encryption of all user data, collecting only minimum necessary user data and implementing principles of lease privilege for all users. On the administration side, mitigation strategies would include doing regular security audits to identify areas of improvement or potential security vulnerabilities and logging all administrative actions for traceability.
